# Generated by Django 3.2.4 on 2022-05-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bidwars', '0003_item_profile_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='media/')),
            ],
        ),
    ]
